name: Replace Redundant Spaces

on:
  push:
    paths:
      - 'Versions/**'

jobs:
  fix-encoding:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create fix script
        run: |
          cat > fix-encoding.js << 'EOF'
          const fs = require('fs').promises;
          const path = require('path');
          
          async function processFile(filePath) {
            try {
              const content = await fs.readFile(filePath, 'utf8');
              const fixedContent = content.replace(/(%20)+/gi, '%20');
              
              if (content !== fixedContent) {
                await fs.writeFile(filePath, fixedContent, 'utf8');
                console.log(`Fixed encoding in: ${filePath}`);
                return true;
              }
              return false;
            } catch (error) {
              console.error(`Error processing ${filePath}:`, error);
              return false;
            }
          }
          
          async function main() {
            const versionsDir = path.join(process.cwd(), 'Versions');
            try {
              const files = await fs.readdir(versionsDir, { recursive: true });
              let changed = false;
              
              for (const file of files) {
                const fullPath = path.join(versionsDir, file);
                const stat = await fs.stat(fullPath);
                
                if (stat.isFile()) {
                  const wasFixed = await processFile(fullPath);
                  changed = changed || wasFixed;
                }
              }
              
              process.exit(changed ? 0 : 78); // Exit code 78 means no changes needed
            } catch (error) {
              console.error('Error:', error);
              process.exit(1);
            }
          }
          
          main();
          EOF
          
      - name: Run fix script
        id: fix
        continue-on-error: true
        run: node fix-encoding.js
        
      - name: Commit changes if needed
        if: steps.fix.outcome == 'success'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Versions/
          git commit -m "fix: normalize URL encoding in Versions directory" || echo "No changes to commit"
          git push 
